insert into public.surahs (number, name_arabic, name_transliteration, name_english, ayah_count, revelation_place) values
(1,'الفاتحة','Al-Fatihah','The Opening',7,'makkah'),
(2,'البقرة','Al-Baqarah','The Cow',286,'madinah'),
(3,'آل عمران','Ali ''Imran','Family of Imran',200,'madinah'),
(4,'النساء','An-Nisa','The Women',176,'madinah'),
(5,'المائدة','Al-Ma''idah','The Table Spread',120,'madinah'),
(6,'الأنعام','Al-An''am','The Cattle',165,'makkah'),
(7,'الأعراف','Al-A''raf','The Heights',206,'makkah'),
(8,'الأنفال','Al-Anfal','The Spoils of War',75,'madinah'),
(9,'التوبة','At-Tawbah','The Repentance',129,'madinah'),
(10,'يونس','Yunus','Jonah',109,'makkah'),
(11,'هود','Hud','Hud',123,'makkah'),
(12,'يوسف','Yusuf','Joseph',111,'makkah'),
(13,'الرعد','Ar-Ra''d','The Thunder',43,'madinah'),
(14,'إبراهيم','Ibrahim','Abraham',52,'makkah'),
(15,'الحجر','Al-Hijr','The Rocky Tract',99,'makkah'),
(16,'النحل','An-Nahl','The Bee',128,'makkah'),
(17,'الإسراء','Al-Isra','The Night Journey',111,'makkah'),
(18,'الكهف','Al-Kahf','The Cave',110,'makkah'),
(19,'مريم','Maryam','Mary',98,'makkah'),
(20,'طه','Taha','Ta-Ha',135,'makkah'),
(21,'الأنبياء','Al-Anbya','The Prophets',112,'makkah'),
(22,'الحج','Al-Hajj','The Pilgrimage',78,'madinah'),
(23,'المؤمنون','Al-Mu''minun','The Believers',118,'makkah'),
(24,'النور','An-Nur','The Light',64,'madinah'),
(25,'الفرقان','Al-Furqan','The Criterion',77,'makkah'),
(26,'الشعراء','Ash-Shu''ara','The Poets',227,'makkah'),
(27,'النمل','An-Naml','The Ant',93,'makkah'),
(28,'القصص','Al-Qasas','The Stories',88,'makkah'),
(29,'العنكبوت','Al-''Ankabut','The Spider',69,'makkah'),
(30,'الروم','Ar-Rum','The Romans',60,'makkah'),
(31,'لقمان','Luqman','Luqman',34,'makkah'),
(32,'السجدة','As-Sajdah','The Prostration',30,'makkah'),
(33,'الأحزاب','Al-Ahzab','The Combined Forces',73,'madinah'),
(34,'سبأ','Saba','Sheba',54,'makkah'),
(35,'فاطر','Fatir','Originator',45,'makkah'),
(36,'يس','Ya-Sin','Ya Sin',83,'makkah'),
(37,'الصافات','As-Saffat','Those Ranged in Ranks',182,'makkah'),
(38,'ص','Sad','The Letter Sad',88,'makkah'),
(39,'الزمر','Az-Zumar','The Groups',75,'makkah'),
(40,'غافر','Ghafir','The Forgiver',85,'makkah'),
(41,'فصلت','Fussilat','Explained in Detail',54,'makkah'),
(42,'الشورى','Ash-Shuraa','The Consultation',53,'makkah'),
(43,'الزخرف','Az-Zukhruf','The Ornaments of Gold',89,'makkah'),
(44,'الدخان','Ad-Dukhan','The Smoke',59,'makkah'),
(45,'الجاثية','Al-Jathiyah','The Crouching',37,'makkah'),
(46,'الأحقاف','Al-Ahqaf','The Wind-Curved Sandhills',35,'makkah'),
(47,'محمد','Muhammad','Muhammad',38,'madinah'),
(48,'الفتح','Al-Fath','The Victory',29,'madinah'),
(49,'الحجرات','Al-Hujurat','The Rooms',18,'madinah'),
(50,'ق','Qaf','Qaf',45,'makkah'),
(51,'الذاريات','Adh-Dhariyat','The Winnowing Winds',60,'makkah'),
(52,'الطور','At-Tur','The Mount',49,'makkah'),
(53,'النجم','An-Najm','The Star',62,'makkah'),
(54,'القمر','Al-Qamar','The Moon',55,'makkah'),
(55,'الرحمن','Ar-Rahman','The Beneficent',78,'madinah'),
(56,'الواقعة','Al-Waqi''ah','The Inevitable',96,'makkah'),
(57,'الحديد','Al-Hadid','The Iron',29,'madinah'),
(58,'المجادلة','Al-Mujadila','The Pleading Woman',22,'madinah'),
(59,'الحشر','Al-Hashr','The Exile',24,'madinah'),
(60,'الممتحنة','Al-Mumtahanah','She That is to be Examined',13,'madinah'),
(61,'الصف','As-Saf','The Ranks',14,'madinah'),
(62,'الجمعة','Al-Jumu''ah','The Congregation',11,'madinah'),
(63,'المنافقون','Al-Munafiqun','The Hypocrites',11,'madinah'),
(64,'التغابن','At-Taghabun','Mutual Disillusion',18,'madinah'),
(65,'الطلاق','At-Talaq','The Divorce',12,'madinah'),
(66,'التحريم','At-Tahrim','The Prohibition',12,'madinah'),
(67,'الملك','Al-Mulk','The Sovereignty',30,'makkah'),
(68,'القلم','Al-Qalam','The Pen',52,'makkah'),
(69,'الحاقة','Al-Haqqah','The Reality',52,'makkah'),
(70,'المعارج','Al-Ma''arij','The Ascending Stairways',44,'makkah'),
(71,'نوح','Nuh','Noah',28,'makkah'),
(72,'الجن','Al-Jinn','The Jinn',28,'makkah'),
(73,'المزمل','Al-Muzzammil','The Enshrouded One',20,'makkah'),
(74,'المدثر','Al-Muddaththir','The Cloaked One',56,'makkah'),
(75,'القيامة','Al-Qiyamah','The Resurrection',40,'makkah'),
(76,'الانسان','Al-Insan','The Man',31,'madinah'),
(77,'المرسلات','Al-Mursalat','The Emissaries',50,'makkah'),
(78,'النبأ','An-Naba','The Tidings',40,'makkah'),
(79,'النازعات','An-Nazi''at','Those Who Drag Forth',46,'makkah'),
(80,'عبس','''Abasa','He Frowned',42,'makkah'),
(81,'التكوير','At-Takwir','The Overthrowing',29,'makkah'),
(82,'الإنفطار','Al-Infitar','The Cleaving',19,'makkah'),
(83,'المطففين','Al-Mutaffifin','The Defrauding',36,'makkah'),
(84,'الإنشقاق','Al-Inshiqaq','The Sundering',25,'makkah'),
(85,'البروج','Al-Buruj','The Mansions of the Stars',22,'makkah'),
(86,'الطارق','At-Tariq','The Nightcomer',17,'makkah'),
(87,'الأعلى','Al-A''la','The Most High',19,'makkah'),
(88,'الغاشية','Al-Ghashiyah','The Overwhelming',26,'makkah'),
(89,'الفجر','Al-Fajr','The Dawn',30,'makkah'),
(90,'البلد','Al-Balad','The City',20,'makkah'),
(91,'الشمس','Ash-Shams','The Sun',15,'makkah'),
(92,'الليل','Al-Layl','The Night',21,'makkah'),
(93,'الضحى','Ad-Duhaa','The Morning Hours',11,'makkah'),
(94,'الشرح','Ash-Sharh','The Relief',8,'makkah'),
(95,'التين','At-Tin','The Fig',8,'makkah'),
(96,'العلق','Al-''Alaq','The Clot',19,'makkah'),
(97,'القدر','Al-Qadr','The Power',5,'makkah'),
(98,'البينة','Al-Bayyinah','The Clear Proof',8,'madinah'),
(99,'الزلزلة','Az-Zalzalah','The Earthquake',8,'madinah'),
(100,'العاديات','Al-''Adiyat','The Courser',11,'makkah'),
(101,'القارعة','Al-Qari''ah','The Calamity',11,'makkah'),
(102,'التكاثر','At-Takathur','The Rivalry in Increase',8,'makkah'),
(103,'العصر','Al-''Asr','The Declining Day',3,'makkah'),
(104,'الهمزة','Al-Humazah','The Traducer',9,'makkah'),
(105,'الفيل','Al-Fil','The Elephant',5,'makkah'),
(106,'قريش','Quraysh','Quraysh',4,'makkah'),
(107,'الماعون','Al-Ma''un','The Small Kindnesses',7,'makkah'),
(108,'الكوثر','Al-Kawthar','The Abundance',3,'makkah'),
(109,'الكافرون','Al-Kafirun','The Disbelievers',6,'makkah'),
(110,'النصر','An-Nasr','The Divine Support',3,'madinah'),
(111,'المسد','Al-Masad','The Palm Fiber',5,'makkah'),
(112,'الإخلاص','Al-Ikhlas','The Sincerity',4,'makkah'),
(113,'الفلق','Al-Falaq','The Daybreak',5,'makkah'),
(114,'الناس','An-Nas','Mankind',6,'makkah')
on conflict (number) do update set
  name_arabic = excluded.name_arabic,
  name_transliteration = excluded.name_transliteration,
  name_english = excluded.name_english,
  ayah_count = excluded.ayah_count,
  revelation_place = excluded.revelation_place;