/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppBooksRouteImport } from './routes/app.books'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppProverbsRouteImport } from './routes/app.proverbs'
import { Route as AppQuotesRouteImport } from './routes/app.quotes'
import { Route as AppWisdomRouteImport } from './routes/app.wisdom'
import { Route as PayWaveRouteImport } from './routes/pay.wave'
import { Route as ApiPublicPrewarmRouteImport } from './routes/api/public/prewarm'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as AppBooksIndexRouteImport } from './routes/app.books.index'
import { Route as AppBooksIdRouteImport } from './routes/app.books.$id'
import { Route as AppReadIdRouteImport } from './routes/app.read.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBooksRoute = AppBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppProverbsRoute = AppProverbsRouteImport.update({
  id: '/proverbs',
  path: '/proverbs',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotesRoute = AppQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AppRoute,
} as any)
const AppWisdomRoute = AppWisdomRouteImport.update({
  id: '/wisdom',
  path: '/wisdom',
  getParentRoute: () => AppRoute,
} as any)
const PayWaveRoute = PayWaveRouteImport.update({
  id: '/pay/wave',
  path: '/pay/wave',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPrewarmRoute = ApiPublicPrewarmRouteImport.update({
  id: '/api/public/prewarm',
  path: '/api/public/prewarm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBooksIndexRoute = AppBooksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBooksRoute,
} as any)
const AppBooksIdRoute = AppBooksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppBooksRoute,
} as any)
const AppReadIdRoute = AppReadIdRouteImport.update({
  id: '/read/$id',
  path: '/read/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/language': typeof LanguageRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRoute
  '/terms': typeof TermsRoute
  '/app/books': typeof AppBooksRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/proverbs': typeof AppProverbsRoute
  '/app/quotes': typeof AppQuotesRoute
  '/app/wisdom': typeof AppWisdomRoute
  '/pay/wave': typeof PayWaveRoute
  '/app/': typeof AppIndexRoute
  '/api/public/prewarm': typeof ApiPublicPrewarmRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/app/books/$id': typeof AppBooksIdRoute
  '/app/read/$id': typeof AppReadIdRoute
  '/app/books/': typeof AppBooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/language': typeof LanguageRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRoute
  '/terms': typeof TermsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/proverbs': typeof AppProverbsRoute
  '/app/quotes': typeof AppQuotesRoute
  '/app/wisdom': typeof AppWisdomRoute
  '/pay/wave': typeof PayWaveRoute
  '/app': typeof AppIndexRoute
  '/api/public/prewarm': typeof ApiPublicPrewarmRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/app/books/$id': typeof AppBooksIdRoute
  '/app/read/$id': typeof AppReadIdRoute
  '/app/books': typeof AppBooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/language': typeof LanguageRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRoute
  '/terms': typeof TermsRoute
  '/app/books': typeof AppBooksRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/proverbs': typeof AppProverbsRoute
  '/app/quotes': typeof AppQuotesRoute
  '/app/wisdom': typeof AppWisdomRoute
  '/pay/wave': typeof PayWaveRoute
  '/app/': typeof AppIndexRoute
  '/api/public/prewarm': typeof ApiPublicPrewarmRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/app/books/$id': typeof AppBooksIdRoute
  '/app/read/$id': typeof AppReadIdRoute
  '/app/books/': typeof AppBooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/language'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/quiz'
    | '/terms'
    | '/app/books'
    | '/app/profile'
    | '/app/proverbs'
    | '/app/quotes'
    | '/app/wisdom'
    | '/pay/wave'
    | '/app/'
    | '/api/public/prewarm'
    | '/api/public/stripe-webhook'
    | '/app/books/$id'
    | '/app/read/$id'
    | '/app/books/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/language'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/quiz'
    | '/terms'
    | '/app/profile'
    | '/app/proverbs'
    | '/app/quotes'
    | '/app/wisdom'
    | '/pay/wave'
    | '/app'
    | '/api/public/prewarm'
    | '/api/public/stripe-webhook'
    | '/app/books/$id'
    | '/app/read/$id'
    | '/app/books'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/language'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/quiz'
    | '/terms'
    | '/app/books'
    | '/app/profile'
    | '/app/proverbs'
    | '/app/quotes'
    | '/app/wisdom'
    | '/pay/wave'
    | '/app/'
    | '/api/public/prewarm'
    | '/api/public/stripe-webhook'
    | '/app/books/$id'
    | '/app/read/$id'
    | '/app/books/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  LanguageRoute: typeof LanguageRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  QuizRoute: typeof QuizRoute
  TermsRoute: typeof TermsRoute
  PayWaveRoute: typeof PayWaveRoute
  ApiPublicPrewarmRoute: typeof ApiPublicPrewarmRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/books': {
      id: '/app/books'
      path: '/books'
      fullPath: '/app/books'
      preLoaderRoute: typeof AppBooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/proverbs': {
      id: '/app/proverbs'
      path: '/proverbs'
      fullPath: '/app/proverbs'
      preLoaderRoute: typeof AppProverbsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quotes': {
      id: '/app/quotes'
      path: '/quotes'
      fullPath: '/app/quotes'
      preLoaderRoute: typeof AppQuotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wisdom': {
      id: '/app/wisdom'
      path: '/wisdom'
      fullPath: '/app/wisdom'
      preLoaderRoute: typeof AppWisdomRouteImport
      parentRoute: typeof AppRoute
    }
    '/pay/wave': {
      id: '/pay/wave'
      path: '/pay/wave'
      fullPath: '/pay/wave'
      preLoaderRoute: typeof PayWaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/prewarm': {
      id: '/api/public/prewarm'
      path: '/api/public/prewarm'
      fullPath: '/api/public/prewarm'
      preLoaderRoute: typeof ApiPublicPrewarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/books/': {
      id: '/app/books/'
      path: '/'
      fullPath: '/app/books/'
      preLoaderRoute: typeof AppBooksIndexRouteImport
      parentRoute: typeof AppBooksRoute
    }
    '/app/books/$id': {
      id: '/app/books/$id'
      path: '/$id'
      fullPath: '/app/books/$id'
      preLoaderRoute: typeof AppBooksIdRouteImport
      parentRoute: typeof AppBooksRoute
    }
    '/app/read/$id': {
      id: '/app/read/$id'
      path: '/read/$id'
      fullPath: '/app/read/$id'
      preLoaderRoute: typeof AppReadIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppBooksRouteChildren {
  AppBooksIdRoute: typeof AppBooksIdRoute
  AppBooksIndexRoute: typeof AppBooksIndexRoute
}

const AppBooksRouteChildren: AppBooksRouteChildren = {
  AppBooksIdRoute: AppBooksIdRoute,
  AppBooksIndexRoute: AppBooksIndexRoute,
}

const AppBooksRouteWithChildren = AppBooksRoute._addFileChildren(
  AppBooksRouteChildren,
)

interface AppRouteChildren {
  AppBooksRoute: typeof AppBooksRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppProverbsRoute: typeof AppProverbsRoute
  AppQuotesRoute: typeof AppQuotesRoute
  AppWisdomRoute: typeof AppWisdomRoute
  AppIndexRoute: typeof AppIndexRoute
  AppReadIdRoute: typeof AppReadIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBooksRoute: AppBooksRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppProverbsRoute: AppProverbsRoute,
  AppQuotesRoute: AppQuotesRoute,
  AppWisdomRoute: AppWisdomRoute,
  AppIndexRoute: AppIndexRoute,
  AppReadIdRoute: AppReadIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  LanguageRoute: LanguageRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  QuizRoute: QuizRoute,
  TermsRoute: TermsRoute,
  PayWaveRoute: PayWaveRoute,
  ApiPublicPrewarmRoute: ApiPublicPrewarmRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
